[network.testnet_parameters]
slow_start_interval = 0
network_magic = [0x5A, 0x53, 0x41, 0x31]
network_name = "ZSA_Testnet_1"
genesis_hash = "077dbb6530d0228c558d4acb8146df937b4c94d89d7c5772c62d891a82c1956b"
no_peers_required = false

[network.testnet_parameters.activation_heights]
NU6 = 1

[consensus]
checkpoint_sync = true

[network]
cache_dir = true
listen_addr = "[::]:18234"
network = "Testnet"
#initial_testnet_peers = ["192.168.18.43:18233"]
initial_testnet_peers = ["103.204.117.164:18233"]

[rpc]
listen_addr = "127.0.0.1:18232"

[state]
cache_dir = "./testnet_zsa_1"
ephemeral = false
